# Generated by Django 4.2.11 on 2025-05-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_story_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
